# 権限の設定
sudo: required

# Dockerを使う
services: docker

# コンテナの起動
before_install:
  - docker-compose up --build -d
  # dockerをサービスレジストリにつなげる
  - docker login -u "$HEROKU_USERNAME" -p "HEROKU_API_KEY" registry.heroku.com

script:
  # DB準備
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  # テスト実行
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

# テストが完了した後のデプロイ
deploy:
  provider: script # herokuの場合 : heroku, dockerの場合 : script
  script:
    docker build -t registy.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registy.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate; # heroku上のレジストリを指定
  on:
    branch: master

# 環境変数
# HEROKU_APP_NAME : 
# HEROKU_USERNAME :
# HEROKU_API_KEY : 